name: Flutter Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - uses: actions/checkout@v4

      # 2️⃣ Instalar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.3"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Iniciar emulador Android ligero
      - name: Run Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29                  # más rápido que 30 en CI
          target: google_apis             # imagen compatible y ligera
          arch: x86                       # funciona sin KVM en GitHub Actions
          profile: pixel_2
          force-avd-creation: true
          disable-animations: true
          emulator-boot-timeout: 600     # esperar hasta 10 minutos
          emulator-options: -no-window -no-audio -no-snapshot -no-boot-anim -gpu swiftshader_indirect
          script: flutter test integration_test/festivities_test.dart -d emulator-5554

      # 5️⃣ Verificar dispositivos conectados (opcional, para debug)
      - name: List connected devices
        run: adb devices
